# Generated by `teeup theme set`. Do not edit; the next theme switch replaces
# it. The zsh default layer sources the file for the current appearance:
#   ~/.local/state/teeup/current/theme/$TEEUP_APPEARANCE/env.sh
export TEEUP_THEME_MODE="{{ mode }}"
export TEEUP_THEME_ACCENT="{{ accent }}"
export BAT_THEME="{{ bat_theme }}"
