#!/usr/bin/env bash
# lazy.sh - the lazy-install seam (spec section 6): shims for commands that
# nothing on the machine provides yet, and the app lookup behind `teeup launch`.
# A shim is a four-line script in $TEEUP_STATE_DIR/shims that hands the call
# to `teeup lazy-run <capability> <command>`. The zsh layer appends that
# directory last on PATH, so a shim fires only when no real binary exists.
# Requires core.sh, files.sh, state.sh, capability.sh and pkg.sh (app_installed
# and app_search_dirs consult pkg_backend and macports_apps_dir).

shims_dir() { printf '%s/shims\n' "$TEEUP_STATE_DIR"; }

# The second line of every shim teeup writes. shims_generate deletes only
# files that carry it, so a stray file dropped into the directory by hand is
# reported rather than removed.
TEEUP_SHIM_MARKER="# teeup lazy shim; regenerated by: teeup configure teeup-runtime"

# lazy_provider <command> -> the tier=lazy capability whose provides= names
# <command>; exit 1 (printing nothing) when there is none. cap_check refuses
# two lazy capabilities providing the same command, so the first hit is the
# only hit.
lazy_provider() {
  local command="$1" name p
  for name in $(cap_list); do
    [[ "$(cap_meta_get "$name" tier)" == "lazy" ]] || continue
    for p in $(cap_meta_get "$name" provides); do
      if [[ "$p" == "$command" ]]; then
        printf '%s\n' "$name"
        return 0
      fi
    done
  done
  return 1
}

# lazy_real_command <command> -> the first executable named <command> on
# PATH outside the shims directory; exit 1 when there is none. PATH is walked
# by hand rather than through `command -v` because the shim itself is on PATH
# and would answer. Honours TEEUP_TEST_MISSING like `have` does, by name and
# by absolute path.
lazy_real_command() {
  local command="$1" shims dir rest candidate
  case " ${TEEUP_TEST_MISSING:-} " in
    *" $command "*) return 1 ;;
  esac
  shims="$(shims_dir)"
  rest="$PATH:"
  while [[ -n "$rest" ]]; do
    dir="${rest%%:*}"
    rest="${rest#*:}"
    [[ -n "$dir" ]] || continue
    [[ "${dir%/}" == "${shims%/}" ]] && continue
    candidate="${dir%/}/$command"
    case " ${TEEUP_TEST_MISSING:-} " in
      *" $candidate "*) continue ;;
    esac
    if [[ -f "$candidate" && -x "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

# lazy_is_tty -> can lazy-run ask a question? Both stdin and stderr must be a
# terminal: a shim run from a script or an editor has neither, and blocking
# on a prompt nobody sees is the failure mode spec section 6 rules out.
# TEEUP_TEST_TTY=yes|no is a test-only hook (the harness has no terminal),
# the same shape as TEEUP_TEST_MISSING in core.sh.
lazy_is_tty() {
  case "${TEEUP_TEST_TTY:-}" in
    yes) return 0 ;;
    no) return 1 ;;
  esac
  [[ -t 0 && -t 2 ]]
}

# shim_write <capability> <command>
# Writes one shim, executable, only when its content changed. TEEUP_PATH is
# baked in as a fallback: a shim reached through PATH normally has TEEUP_PATH
# from ~/.config/teeup/env, but a stripped environment (an IDE's process
# runner, a cron job) must still find the checkout. The path is %q-escaped
# and lands on its own assignment line, so a space, quote or dollar in the
# checkout path cannot break the exec line, which only ever expands
# variables.
shim_write() {
  local cap="$1" command="$2" file teeup_path_q
  file="$(shims_dir)/$command"
  teeup_path_q="$(printf '%q' "$TEEUP_PATH")"
  write_managed_file "$file" "shim for $command, capability $cap" <<SHIM
#!/bin/bash
$TEEUP_SHIM_MARKER
teeup_path=$teeup_path_q
exec "\${TEEUP_PATH:-\$teeup_path}/bin/teeup" lazy-run $cap $command "\$@"
SHIM
  [[ "$DRY_RUN" == "true" ]] || chmod 755 "$file"
}

# shims_generate
# One shim per command in provides= of every tier=lazy capability, stale
# shims removed. Idempotent; under DRY_RUN it prints what it would write and
# remove. A capability skipped by TEEUP_SKIP gets no shims: on that machine
# the command really is "not found", which is the honest answer. Nothing here
# is hard-coded: a lazy capability added by any later plan gets its shims on
# the next `teeup configure teeup-runtime`.
shims_generate() {
  local dir wanted=" " name p f base
  dir="$(shims_dir)"
  [[ -d "$dir" ]] || run_cmd mkdir -p "$dir"
  for name in $(cap_list); do
    [[ "$(cap_meta_get "$name" tier)" == "lazy" ]] || continue
    if cap_skipped "$name"; then
      log "No shims for $name (TEEUP_SKIP)"
      continue
    fi
    for p in $(cap_meta_get "$name" provides); do
      shim_write "$name" "$p"
      wanted="$wanted$p "
    done
  done
  for f in "$dir"/*; do
    [[ -e "$f" ]] || continue
    base="${f##*/}"
    case "$wanted" in *" $base "*) continue ;; esac
    if [[ -f "$f" ]] && sed -n 2p "$f" | grep -qxF "$TEEUP_SHIM_MARKER"; then
      run_cmd rm -f "$f"
      [[ "$DRY_RUN" == "true" ]] || ok "Removed stale shim: $base"
    else
      warn "Not a teeup shim, leaving it alone: $f"
    fi
  done
  return 0
}

# --- teeup launch -------------------------------------------------------------

# cap_apps <capability> -> one application name per line from apps=. The
# separator is ";" rather than a space because app names contain spaces
# ("Visual Studio Code", "Google Chrome"); a single name needs no separator.
cap_apps() {
  local rest app
  rest="$(cap_meta_get "$1" apps);"
  while [[ -n "$rest" ]]; do
    app="${rest%%;*}"
    rest="${rest#*;}"
    app="${app#"${app%%[![:space:]]*}"}"
    app="${app%"${app##*[![:space:]]}"}"
    [[ -n "$app" ]] && printf '%s\n' "$app"
  done
  return 0
}

# app_installed <app name> -> is <app>.app present where casks -- or, on a
# MacPorts machine, an aqua port's Portfile -- put it?
# TEEUP_APPS_DIR is the test hook aerospace already uses for /Applications;
# ~/Applications is where a cask lands when HOMEBREW_CASK_OPTS points it there.
# macports_apps_dir (lib/pkg.sh) is consulted on a MacPorts backend, because a
# MacPorts aqua port (emacs-app, wezterm, ...) moves its .app into
# applications_dir at destroot time and never touches /Applications (B1):
# without this, `teeup launch` calls an installed app "not found" and
# reinstalls it on every call.
app_installed() {
  [[ -d "${TEEUP_APPS_DIR:-/Applications}/$1.app" || -d "$HOME/Applications/$1.app" ]] && return 0
  [[ "$(pkg_backend)" == "macports" ]] && [[ -d "$(macports_apps_dir)/$1.app" ]]
}

# app_search_dirs -> every directory app_installed actually checked on this
# machine, comma-separated, for an honest "still not found" message (B1).
# MacPorts' applications_dir is named only on a MacPorts backend: naming it
# unconditionally would claim teeup looked somewhere it never checks on a
# Homebrew machine.
app_search_dirs() {
  local dirs="${TEEUP_APPS_DIR:-/Applications}, $HOME/Applications"
  if [[ "$(pkg_backend)" == "macports" ]]; then
    dirs="$dirs, $(macports_apps_dir)"
  fi
  printf '%s\n' "$dirs"
}

# app_match_in_cap <capability> <wanted> -> the entry from <capability>'s
# apps= that <wanted> names, matched the same case-insensitive,
# ".app"-suffix-optional way launch_resolve matches by app name. Exit 1 (M6)
# when <wanted> is not one of them -- typically because it was the
# capability's own name, not an app -- so the caller can fall back to the
# capability's first app instead of always opening that one regardless of
# which app the user actually asked for.
app_match_in_cap() {
  local cap="$1" wanted="${2%.app}" key app
  key="$(printf '%s' "$wanted" | tr '[:upper:]' '[:lower:]')"
  while IFS= read -r app; do
    if [[ "$(printf '%s' "$app" | tr '[:upper:]' '[:lower:]')" == "$key" ]]; then
      printf '%s\n' "$app"
      return 0
    fi
  done < <(cap_apps "$cap")
  return 1
}

# launch_resolve <app|capability> -> the capability to launch; exit 1 with a
# message when nothing matches. A capability name wins, but only on an exact,
# case-sensitive match against the directory names cap_list lists: macOS's
# default case-insensitive disks make `[[ -f capabilities/$name/capability ]]`
# true for any case variant of a real directory name (`Cursor` resolves the
# same file as `cursor`), which would let a mis-cased name through with its
# original casing still attached, letting `TEEUP_SKIP` miss it downstream.
# Comparing against the listed names keeps the match case-sensitive on every
# disk. Otherwise every capability's app names are compared
# case-insensitively, with an optional ".app" suffix on the argument ignored.
launch_resolve() {
  local wanted="${1%.app}" name
  if cap_list | grep -qxF -- "$wanted"; then
    if [[ -z "$(cap_meta_get "$wanted" apps)" ]]; then
      err "$wanted has no apps= entry, so there is nothing to launch."
      return 1
    fi
    printf '%s\n' "$wanted"
    return 0
  fi
  for name in $(cap_list); do
    if app_match_in_cap "$name" "$wanted" >/dev/null; then
      printf '%s\n' "$name"
      return 0
    fi
  done
  err "No capability provides an app named '$1' (try: teeup list)."
  return 1
}
