#!/usr/bin/env bash
# mise.sh - mise-managed tools: the global-state check every mise consumer
# needs, the on-first-call wrappers for AI CLIs, and `teeup install dev-env`.
# Requires core.sh, files.sh, state.sh and pkg.sh.
#
# Every mise call here runs with `-C /` ("Change directory before running
# command") except the `mise x` line inside a wrapper, which must run in the
# caller's directory. mise resolves its configuration stack from the current
# directory, so run from inside a project whose own mise.toml also asks for
# the tool, `mise ls --global` hides the global row entirely (verified on
# 2026.9.4: the project's request shadows the global one), `mise install`
# resolves the project's version and `mise where` reports the project's
# install. From `/` no project config is in reach and the global config
# (MISE_CONFIG_DIR or ~/.config/mise, unaffected by -C) is the whole stack.

# mise_global_state <tool> -> installed | requested | absent
# Two questions, because mise answers them separately. `mise ls --global`
# ("Only show tool versions currently specified in the global mise.toml")
# says whether the global config *requests* the tool, but it lists requested
# versions whether or not they are installed, so a row there is no proof of a
# binary: an interrupted install, a manual uninstall or a wiped MISE_DATA_DIR
# all leave the request behind with the tool gone. `--installed` ("Hides
# tools defined in mise.toml but not installed") answers the second question;
# with both flags and the tool name, a row comes back only when the tool is
# requested globally and on disk. A mise that rejects --installed gets
# `mise where <tool>` instead, which fails when the requested version is not
# installed. A mise too old for --global exits non-zero on it; there, the
# global config file (the same file `mise use -g` writes) answers the first
# question and `mise where` the second.
mise_global_state() {
  local tool="$1" config_file rows
  # MISE_GLOBAL_CONFIG_FILE names the file outright and wins over
  # MISE_CONFIG_DIR in mise itself, so the fallback has to read the same file
  # mise would (I2: reading the wrong one reports "absent" for a tool that is
  # requested, and `use -g` then rewrites a pinned version).
  config_file="${MISE_GLOBAL_CONFIG_FILE:-${MISE_CONFIG_DIR:-$(user_config_dir)/mise}/config.toml}"
  if rows="$(mise -C / ls --global 2>/dev/null)"; then
    if printf '%s\n' "$rows" | awk '{print $1}' | grep -qx "$tool"; then
      if rows="$(mise -C / ls --global --installed "$tool" 2>/dev/null)"; then
        if printf '%s\n' "$rows" | awk '{print $1}' | grep -qx "$tool"; then
          echo installed
          return 0
        fi
      elif mise -C / where "$tool" >/dev/null 2>&1; then
        echo installed
        return 0
      fi
      echo requested
      return 0
    fi
  elif [[ -f "$config_file" ]]; then
    if grep -qE "^[[:space:]]*(\"$tool\"|$tool)[[:space:]]*=" "$config_file"; then
      if mise -C / where "$tool" >/dev/null 2>&1; then echo installed; else echo requested; fi
      return 0
    fi
  fi
  echo absent
}

# mise_ensure_global <tool> [version]
#   requested and installed  -> nothing to do
#   requested but missing    -> `mise install` (honours the pinned version;
#                               `mise use -g` would rewrite the request)
#   not requested            -> `mise use -g` (writes the request and installs)
# Warns and returns 1 when mise cannot install it, so a caller under `set -e`
# decides whether that is fatal.
mise_ensure_global() {
  local tool="$1" version="${2:-}"
  case "$(mise_global_state "$tool")" in
    installed)
      log "Already installed through mise: $tool"
      ;;
    requested)
      log "$tool is requested by the global mise config but not installed; installing it."
      run_cmd mise -C / install "$tool" || { warn "Could not install $tool through mise."; return 1; }
      ;;
    *)
      run_cmd mise -C / use -g "$tool${version:+@$version}" || { warn "Could not install $tool through mise."; return 1; }
      ;;
  esac
}

# The second line of every wrapper teeup writes. Keep this literal stable: it
# is the ownership record on machines that configured the old aggregate `ai`
# capability. Help text is generated from the owner argument instead.
TEEUP_MISE_WRAPPER_MARKER="# teeup mise wrapper; regenerated by: teeup configure ai"

# mise_wrapper_write <owner> <display-name> <command> <tool> [runtime...]
# Writes ~/.local/bin/<command>. Missing tools are installed from / so a
# project mise.toml cannot redirect the global request. The first progress line
# reaches stderr immediately; install output and outcomes also append to the
# lazy log. A requested-but-missing tool uses `mise install`, retaining a pin.
# When the wrapper runs as the command of an outer run_logged (which sets
# TEEUP_RUN_LOG_CAPTURED=true and already tees this process's stdout/stderr),
# it prints and runs without its own append or tee, matching the "nested
# runners do not append or tee independently" rule lib/core.sh's run_logged
# follows for the same reason.
mise_wrapper_write() {
  local owner="$1" display_name="$2" command="$3" tool="$4" file t tools
  shift 4
  tools="$* $tool"
  tools="${tools# }"
  for t in "$owner" "$command" $tools; do
    if ! [[ "$t" =~ ^[A-Za-z0-9][A-Za-z0-9_.+-]*$ ]]; then
      err "mise_wrapper_write: '$t' is not a plain capability, command or tool name"
      return 1
    fi
  done
  file="$HOME/.local/bin/$command"
  # shellcheck disable=SC2034  # read by capability configure scripts
  MISE_WRAPPER_WRITTEN=false
  if [[ -e "$file" || -L "$file" ]] && ! sed -n 2p "$file" 2>/dev/null | grep -qxF "$TEEUP_MISE_WRAPPER_MARKER"; then
    warn "Keeping $file: it was not written by teeup. Remove it and run teeup configure $owner to use the mise wrapper."
    return 0
  fi
  [[ -d "$HOME/.local/bin" ]] || run_cmd mkdir -p "$HOME/.local/bin"
  if write_managed_file "$file" "mise wrapper for $command" <<WRAPPER
#!/bin/bash
$TEEUP_MISE_WRAPPER_MARKER
# Installs $tools through mise on the first call, then runs $command.
export MISE_MINIMUM_RELEASE_AGE=0
if ! command -v mise >/dev/null 2>&1; then
  printf '%s\\n' "$command is installed through mise, which is not on PATH. Run: teeup install mise" >&2
  exit 127
fi
teeup_requested() {
  teeup_rows=""
  if teeup_rows="\$(mise -C / ls --global 2>/dev/null)"; then
    printf '%s\\n' "\$teeup_rows" | awk '{print \$1}' | grep -qx "\$1"
    return \$?
  fi
  teeup_cfg="\${MISE_GLOBAL_CONFIG_FILE:-\${MISE_CONFIG_DIR:-\${XDG_CONFIG_HOME:-\$HOME/.config}/mise}/config.toml}"
  [ -f "\$teeup_cfg" ] || return 1
  grep -qE "^[[:space:]]*(\"\$1\"|\$1)[[:space:]]*=" "\$teeup_cfg"
}

teeup_missing=""
for teeup_tool in $tools; do
  if ! mise -C / where "\$teeup_tool" >/dev/null 2>&1; then
    teeup_missing="\$teeup_missing \$teeup_tool"
  fi
done
teeup_missing="\${teeup_missing# }"

if [ "\${DRY_RUN:-false}" = "true" ] && [ -n "\$teeup_missing" ]; then
  printf '%s\\n' "[DRY-RUN] Would install \$teeup_missing through mise, then run $command." >&2
  exit 0
fi

if [ -n "\$teeup_missing" ]; then
  teeup_log_ready=false
  if [ "\${TEEUP_RUN_LOG_CAPTURED:-false}" != "true" ]; then
    teeup_state_dir="\${TEEUP_STATE_DIR:-\${XDG_STATE_HOME:-\$HOME/.local/state}/teeup}"
    teeup_log_file="\${TEEUP_LOG_FILE:-\$teeup_state_dir/logs/lazy.log}"
    if mkdir -p "\$(dirname "\$teeup_log_file")" 2>/dev/null && { : >> "\$teeup_log_file"; } 2>/dev/null; then
      teeup_log_ready=true
    else
      printf '%s\\n' "Could not write the lazy install log: \$teeup_log_file" >&2
    fi
  fi
  teeup_log_only() {
    [ "\$teeup_log_ready" = "true" ] || return 0
    printf '[%s] %s\\n' "\$(date '+%Y-%m-%d %H:%M:%S')" "\$*" >> "\$teeup_log_file"
  }
  teeup_run_install() {
    teeup_rc=0
    if [ "\$teeup_log_ready" = "true" ]; then
      "\$@" 2>&1 | tee -a "\$teeup_log_file" >&2
      teeup_rc="\${PIPESTATUS[0]}"
    else
      "\$@" || teeup_rc=\$?
    fi
    return "\$teeup_rc"
  }
  printf '%s\\n' "Installing $display_name through mise (first run, can take a minute)..." >&2
  teeup_log_only "Installing $display_name through mise (first run, can take a minute)..."
  trap 'teeup_log_only "Install interrupted for $display_name through mise."; exit 130' INT TERM
  for teeup_tool in $tools; do
    if mise -C / where "\$teeup_tool" >/dev/null 2>&1; then
      continue
    fi
    teeup_rc=0
    if teeup_requested "\$teeup_tool"; then
      teeup_run_install mise -C / install "\$teeup_tool" || teeup_rc=\$?
    else
      teeup_run_install mise -C / use -g --quiet "\$teeup_tool" || teeup_rc=\$?
    fi
    if [ "\$teeup_rc" -ne 0 ]; then
      teeup_log_only "Install failed for $display_name through mise (exit \$teeup_rc)."
      trap - INT TERM
      exit "\$teeup_rc"
    fi
  done
  trap - INT TERM
  teeup_log_only "Installed $display_name through mise."
fi

# There is no mutation left to withhold once every tool is installed.
exec mise x $tools -- $command "\$@"
WRAPPER
  then
    # shellcheck disable=SC2034  # read by capability configure scripts
    MISE_WRAPPER_WRITTEN=true
    [[ "$DRY_RUN" == "true" ]] || chmod 755 "$file"
  fi
}

# mise_tool_unuse <tool>
# Takes <tool> out of the global mise config and prunes its install -- what
# `teeup remove` owes a tool its wrapper asked for with `mise use -g`.
# Removing only the wrapper left the tool installed and still requested, so
# the next `teeup update` (mise upgrade) put it back (real Mac, 2026-09-26).
# A tool the global config does not request is left alone: teeup never asked
# for it. Only the capability's own tool is passed here, never a shared
# runtime such as node. 0 done or nothing to do; 1 the unuse failed.
mise_tool_unuse() {
  local tool="$1"
  if ! [[ "$tool" =~ ^[A-Za-z0-9][A-Za-z0-9_.+-]*$ ]]; then
    err "mise_tool_unuse: '$tool' is not a plain tool name"
    return 1
  fi
  # mise_global_state falls back to reading the config file when mise itself
  # cannot answer, so a tool still requested there is found even with mise
  # off PATH. Reporting success then would clear the removal marker while the
  # request stays, and the next `teeup update` with mise back would restore
  # the tool with no way to retry the remove (Codex on #46).
  if [[ "$(mise_global_state "$tool")" == "absent" ]]; then
    return 0
  fi
  # A dry run only previews the unuse through run_cmd, which needs no mise.
  if [[ "$DRY_RUN" != "true" ]] && ! have mise; then
    warn "mise is not on PATH, so $tool is still requested in the global mise config. Once mise is back, run: mise unuse -g $tool"
    return 1
  fi
  if ! run_cmd mise -C / unuse -g "$tool"; then
    warn "Could not remove $tool from the global mise config. Run: mise unuse -g $tool"
    return 1
  fi
  ok_unless_dry "Removed $tool from the global mise config"
}

# mise_wrapper_remove <owner> <command>
# Deletes only a wrapper carrying the stable marker. Absence and a foreign file
# are successful no-ops; an owned path that remains after rm is a failure.
mise_wrapper_remove() {
  local owner="$1" command="$2" file="$HOME/.local/bin/$2" t
  for t in "$owner" "$command"; do
    if ! [[ "$t" =~ ^[A-Za-z0-9][A-Za-z0-9_.+-]*$ ]]; then
      err "mise_wrapper_remove: '$t' is not a plain capability or command name"
      return 1
    fi
  done
  if [[ ! -e "$file" && ! -L "$file" ]]; then
    log "No teeup-written wrapper found for $command."
    return 0
  fi
  if ! sed -n 2p "$file" 2>/dev/null | grep -qxF "$TEEUP_MISE_WRAPPER_MARKER"; then
    warn "Keeping $file: it was not written by teeup."
    return 0
  fi
  if ! run_cmd rm -f "$file"; then
    warn "Could not remove $file. Fix its permissions and try again."
    return 1
  fi
  if [[ "$DRY_RUN" != "true" && ( -e "$file" || -L "$file" ) ]]; then
    warn "$file is still there. Remove it and try again."
    return 1
  fi
  ok_unless_dry "Removed the mise wrapper: $command"
}

# --- teeup install dev-env ---------------------------------------------------

TEEUP_DEV_ENVS="python node java ruby rust go"

# dev_env_install <python|node|java|ruby|rust|go>
# Runtimes get no shims (spec section 4a: macOS ships python3, ruby and java,
# so a PATH-last shim could never fire) and arrive only through this command.
# Everything is `mise use --global`; Python brings uv along; Rust goes
# through mise's rust backend, which drives rustup (installing it into
# ~/.rustup and ~/.cargo when no rustup is on PATH), so the same call works
# on a Homebrew and on a MacPorts machine.
dev_env_install() {
  local lang="${1:-}" l known=false
  for l in $TEEUP_DEV_ENVS; do
    if [[ "$l" == "$lang" ]]; then known=true; fi
  done
  if [[ "$known" != "true" ]]; then
    err "Usage: teeup install dev-env <python|node|java|ruby|rust|go>"
    return 1
  fi
  if ! have mise; then
    err "mise is not installed; run: teeup install mise"
    return 1
  fi
  case "$lang" in
    python)
      mise_ensure_global python latest || return 1
      mise_ensure_global uv latest || return 1
      ;;
    node) mise_ensure_global node latest || return 1 ;;
    java)
      mise_ensure_global java latest || return 1
      # javav (capabilities/zsh/default/functions) only exists once the zsh
      # capability has installed it; naming it unconditionally would send a
      # bash user, or anyone who skipped zsh, to a command that is not there
      # (M4, same class as I4).
      if state_done check "cap-zsh"; then
        log "Switch Java per shell with: javav 21 (Corretto 21), javav zulu-17, javav (show)"
      else
        log "Switch Java per shell with: mise use java@<spec> (install teeup's zsh layer for the javav shortcut: teeup install zsh)"
      fi
      ;;
    ruby) mise_ensure_global ruby latest || return 1 ;;
    rust) mise_ensure_global rust latest || return 1 ;;
    go) mise_ensure_global go latest || return 1 ;;
  esac
  state_done mark "dev-env-$lang"
  # "the next prompt in this shell has it (mise activate)" is only true once
  # the zsh capability's `mise activate` is actually loaded (M4): on a bash
  # session, or a Mac that skipped zsh, nothing here reruns automatically.
  if state_done check "cap-zsh"; then
    ok_unless_dry "$lang is ready: the next prompt in this shell has it (mise activate); other shells after a new terminal."
  else
    ok_unless_dry "$lang is ready through mise. Install teeup's zsh layer (teeup install zsh) so new shells pick it up automatically; for now use: mise x $lang -- ..., or mise use $lang in this shell."
  fi
}

# dev_env_installed -> the dev-envs this machine has marked, one per line.
dev_env_installed() {
  local l
  for l in $TEEUP_DEV_ENVS; do
    state_done check "dev-env-$l" && printf '%s\n' "$l"
  done
  return 0
}

# mise_upgrade
# `teeup update`'s mise step (spec section 9): upgrade every tool the global
# config holds, which is the AI CLIs' tools, the dev-env runtimes and anything
# else installed with `mise use -g`. `-C /` keeps it to that config, the rule
# every mise call outside a wrapper follows. A machine without mise is not an
# error: mise is a core capability, but `teeup update` also runs on a machine
# where it is in TEEUP_SKIP.
mise_upgrade() {
  if ! have mise; then
    log "mise is not installed here; skipping the mise upgrade."
    return 0
  fi
  run_cmd mise -C / upgrade || { warn "mise upgrade returned non-zero."; return 1; }
}
