#!/usr/bin/env bash
# mise.sh - mise-managed tools: the global-state check every mise consumer
# needs, the on-first-call wrappers for AI CLIs, and `teeup install dev-env`.
# Requires core.sh, files.sh, state.sh and pkg.sh.
#
# Every mise call here runs with `-C /` ("Change directory before running
# command") except the `mise x` line inside a wrapper, which must run in the
# caller's directory. mise resolves its configuration stack from the current
# directory, so run from inside a project whose own mise.toml also asks for
# the tool, `mise ls --global` hides the global row entirely (verified on
# 2026.9.4: the project's request shadows the global one), `mise install`
# resolves the project's version and `mise where` reports the project's
# install. From `/` no project config is in reach and the global config
# (MISE_CONFIG_DIR or ~/.config/mise, unaffected by -C) is the whole stack.

# mise_global_state <tool> -> installed | requested | absent
# Two questions, because mise answers them separately. `mise ls --global`
# ("Only show tool versions currently specified in the global mise.toml")
# says whether the global config *requests* the tool, but it lists requested
# versions whether or not they are installed, so a row there is no proof of a
# binary: an interrupted install, a manual uninstall or a wiped MISE_DATA_DIR
# all leave the request behind with the tool gone. `--installed` ("Hides
# tools defined in mise.toml but not installed") answers the second question;
# with both flags and the tool name, a row comes back only when the tool is
# requested globally and on disk. A mise that rejects --installed gets
# `mise where <tool>` instead, which fails when the requested version is not
# installed. A mise too old for --global exits non-zero on it; there, the
# global config file (the same file `mise use -g` writes) answers the first
# question and `mise where` the second.
mise_global_state() {
  local tool="$1" config_file rows
  # MISE_GLOBAL_CONFIG_FILE names the file outright and wins over
  # MISE_CONFIG_DIR in mise itself, so the fallback has to read the same file
  # mise would (I2: reading the wrong one reports "absent" for a tool that is
  # requested, and `use -g` then rewrites a pinned version).
  config_file="${MISE_GLOBAL_CONFIG_FILE:-${MISE_CONFIG_DIR:-$(user_config_dir)/mise}/config.toml}"
  if rows="$(mise -C / ls --global 2>/dev/null)"; then
    if printf '%s\n' "$rows" | awk '{print $1}' | grep -qx "$tool"; then
      if rows="$(mise -C / ls --global --installed "$tool" 2>/dev/null)"; then
        if printf '%s\n' "$rows" | awk '{print $1}' | grep -qx "$tool"; then
          echo installed
          return 0
        fi
      elif mise -C / where "$tool" >/dev/null 2>&1; then
        echo installed
        return 0
      fi
      echo requested
      return 0
    fi
  elif [[ -f "$config_file" ]]; then
    if grep -qE "^[[:space:]]*(\"$tool\"|$tool)[[:space:]]*=" "$config_file"; then
      if mise -C / where "$tool" >/dev/null 2>&1; then echo installed; else echo requested; fi
      return 0
    fi
  fi
  echo absent
}

# mise_ensure_global <tool> [version]
#   requested and installed  -> nothing to do
#   requested but missing    -> `mise install` (honours the pinned version;
#                               `mise use -g` would rewrite the request)
#   not requested            -> `mise use -g` (writes the request and installs)
# Warns and returns 1 when mise cannot install it, so a caller under `set -e`
# decides whether that is fatal.
mise_ensure_global() {
  local tool="$1" version="${2:-}"
  case "$(mise_global_state "$tool")" in
    installed)
      log "Already installed through mise: $tool"
      ;;
    requested)
      log "$tool is requested by the global mise config but not installed; installing it."
      run_cmd mise -C / install "$tool" || { warn "Could not install $tool through mise."; return 1; }
      ;;
    *)
      run_cmd mise -C / use -g "$tool${version:+@$version}" || { warn "Could not install $tool through mise."; return 1; }
      ;;
  esac
}

# The second line of every wrapper teeup writes. Keep this literal stable: it
# is the ownership record on machines that configured the old aggregate `ai`
# capability. Help text is generated from the owner argument instead.
TEEUP_MISE_WRAPPER_MARKER="# teeup mise wrapper; regenerated by: teeup configure ai"

# mise_wrapper_write <owner> <display-name> <command> <tool> [runtime...]
# Writes ~/.local/bin/<command>. Missing tools are installed from / so a
# project mise.toml cannot redirect the global request. The first progress line
# reaches stderr immediately; install output and outcomes also append to the
# lazy log. A requested-but-missing tool uses `mise install`, retaining a pin.
# When the wrapper runs as the command of an outer run_logged (which sets
# TEEUP_RUN_LOG_CAPTURED=true and already tees this process's stdout/stderr),
# it prints and runs without its own append or tee, matching the "nested
# runners do not append or tee independently" rule lib/core.sh's run_logged
# follows for the same reason.
mise_wrapper_write() {
  local owner="$1" display_name="$2" command="$3" tool="$4" file t tools
  shift 4
  tools="$* $tool"
  tools="${tools# }"
  for t in "$owner" "$command" $tools; do
    if ! [[ "$t" =~ ^[A-Za-z0-9][A-Za-z0-9_.+-]*$ ]]; then
      err "mise_wrapper_write: '$t' is not a plain capability, command or tool name"
      return 1
    fi
  done
  file="$HOME/.local/bin/$command"
  # shellcheck disable=SC2034  # read by capability configure scripts
  MISE_WRAPPER_WRITTEN=false
  if [[ -e "$file" || -L "$file" ]] && ! sed -n 2p "$file" 2>/dev/null | grep -qxF "$TEEUP_MISE_WRAPPER_MARKER"; then
    warn "Keeping $file: it was not written by teeup. Remove it and run teeup configure $owner to use the mise wrapper."
    return 0
  fi
  [[ -d "$HOME/.local/bin" ]] || run_cmd mkdir -p "$HOME/.local/bin"
  if write_managed_file "$file" "mise wrapper for $command" <<WRAPPER
#!/bin/bash
$TEEUP_MISE_WRAPPER_MARKER
# Installs $tools through mise on the first call, then runs $command.
export MISE_MINIMUM_RELEASE_AGE=0
if ! command -v mise >/dev/null 2>&1; then
  printf '%s\\n' "$command is installed through mise, which is not on PATH. Run: teeup install mise" >&2
  exit 127
fi
teeup_requested() {
  teeup_rows=""
  if teeup_rows="\$(mise -C / ls --global 2>/dev/null)"; then
    printf '%s\\n' "\$teeup_rows" | awk '{print \$1}' | grep -qx "\$1"
    return \$?
  fi
  teeup_cfg="\${MISE_GLOBAL_CONFIG_FILE:-\${MISE_CONFIG_DIR:-\${XDG_CONFIG_HOME:-\$HOME/.config}/mise}/config.toml}"
  [ -f "\$teeup_cfg" ] || return 1
  grep -qE "^[[:space:]]*(\"\$1\"|\$1)[[:space:]]*=" "\$teeup_cfg"
}

teeup_missing=""
for teeup_tool in $tools; do
  if ! mise -C / where "\$teeup_tool" >/dev/null 2>&1; then
    teeup_missing="\$teeup_missing \$teeup_tool"
  fi
done
teeup_missing="\${teeup_missing# }"

if [ "\${DRY_RUN:-false}" = "true" ] && [ -n "\$teeup_missing" ]; then
  printf '%s\\n' "[DRY-RUN] Would install \$teeup_missing through mise, then run $command." >&2
  exit 0
fi

if [ -n "\$teeup_missing" ]; then
  teeup_log_ready=false
  if [ "\${TEEUP_RUN_LOG_CAPTURED:-false}" != "true" ]; then
    teeup_state_dir="\${TEEUP_STATE_DIR:-\${XDG_STATE_HOME:-\$HOME/.local/state}/teeup}"
    teeup_log_file="\${TEEUP_LOG_FILE:-\$teeup_state_dir/logs/lazy.log}"
    if mkdir -p "\$(dirname "\$teeup_log_file")" 2>/dev/null && { : >> "\$teeup_log_file"; } 2>/dev/null; then
      teeup_log_ready=true
    else
      printf '%s\\n' "Could not write the lazy install log: \$teeup_log_file" >&2
    fi
  fi
  teeup_log_only() {
    [ "\$teeup_log_ready" = "true" ] || return 0
    printf '[%s] %s\\n' "\$(date '+%Y-%m-%d %H:%M:%S')" "\$*" >> "\$teeup_log_file"
  }
  teeup_run_install() {
    teeup_rc=0
    if [ "\$teeup_log_ready" = "true" ]; then
      "\$@" 2>&1 | tee -a "\$teeup_log_file" >&2
      teeup_rc="\${PIPESTATUS[0]}"
    else
      "\$@" || teeup_rc=\$?
    fi
    return "\$teeup_rc"
  }
  printf '%s\\n' "Installing $display_name through mise (first run, can take a minute)..." >&2
  teeup_log_only "Installing $display_name through mise (first run, can take a minute)..."
  trap 'teeup_log_only "Install interrupted for $display_name through mise."; exit 130' INT TERM
  for teeup_tool in $tools; do
    if mise -C / where "\$teeup_tool" >/dev/null 2>&1; then
      continue
    fi
    teeup_rc=0
    if teeup_requested "\$teeup_tool"; then
      teeup_run_install mise -C / install "\$teeup_tool" || teeup_rc=\$?
    else
      teeup_run_install mise -C / use -g --quiet "\$teeup_tool" || teeup_rc=\$?
    fi
    if [ "\$teeup_rc" -ne 0 ]; then
      teeup_log_only "Install failed for $display_name through mise (exit \$teeup_rc)."
      trap - INT TERM
      exit "\$teeup_rc"
    fi
  done
  trap - INT TERM
  teeup_log_only "Installed $display_name through mise."
fi

# There is no mutation left to withhold once every tool is installed.
exec mise x $tools -- $command "\$@"
WRAPPER
  then
    # shellcheck disable=SC2034  # read by capability configure scripts
    MISE_WRAPPER_WRITTEN=true
    [[ "$DRY_RUN" == "true" ]] || chmod 755 "$file"
  fi
}

# mise_tool_unuse <tool>
# Takes <tool> out of the global mise config and prunes its install -- what
# `teeup remove` owes a tool its wrapper asked for with `mise use -g`.
# Removing only the wrapper left the tool installed and still requested, so
# the next `teeup update` (mise upgrade) put it back (real Mac, 2026-09-26).
# A tool the global config does not request is left alone: teeup never asked
# for it. Only the capability's own tool is passed here, never a shared
# runtime such as node. 0 done or nothing to do; 1 the unuse failed.
mise_tool_unuse() {
  local tool="$1"
  if ! [[ "$tool" =~ ^[A-Za-z0-9][A-Za-z0-9_.+-]*$ ]]; then
    err "mise_tool_unuse: '$tool' is not a plain tool name"
    return 1
  fi
  # mise_global_state falls back to reading the config file when mise itself
  # cannot answer, so a tool still requested there is found even with mise
  # off PATH. Reporting success then would clear the removal marker while the
  # request stays, and the next `teeup update` with mise back would restore
  # the tool with no way to retry the remove (Codex on #46).
  if [[ "$(mise_global_state "$tool")" == "absent" ]]; then
    return 0
  fi
  # A dry run only previews the unuse through run_cmd, which needs no mise.
  if [[ "$DRY_RUN" != "true" ]] && ! have mise; then
    warn "mise is not on PATH, so $tool is still requested in the global mise config. Once mise is back, run: mise unuse -g $tool"
    return 1
  fi
  if ! run_cmd mise -C / unuse -g "$tool"; then
    warn "Could not remove $tool from the global mise config. Run: mise unuse -g $tool"
    return 1
  fi
  ok_unless_dry "Removed $tool from the global mise config"
}

# mise_wrapper_remove <owner> <command>
# Deletes only a wrapper carrying the stable marker. Absence and a foreign file
# are successful no-ops; an owned path that remains after rm is a failure.
mise_wrapper_remove() {
  local owner="$1" command="$2" file="$HOME/.local/bin/$2" t
  for t in "$owner" "$command"; do
    if ! [[ "$t" =~ ^[A-Za-z0-9][A-Za-z0-9_.+-]*$ ]]; then
      err "mise_wrapper_remove: '$t' is not a plain capability or command name"
      return 1
    fi
  done
  if [[ ! -e "$file" && ! -L "$file" ]]; then
    log "No teeup-written wrapper found for $command."
    return 0
  fi
  if ! sed -n 2p "$file" 2>/dev/null | grep -qxF "$TEEUP_MISE_WRAPPER_MARKER"; then
    warn "Keeping $file: it was not written by teeup."
    return 0
  fi
  if ! run_cmd rm -f "$file"; then
    warn "Could not remove $file. Fix its permissions and try again."
    return 1
  fi
  if [[ "$DRY_RUN" != "true" && ( -e "$file" || -L "$file" ) ]]; then
    warn "$file is still there. Remove it and try again."
    return 1
  fi
  ok_unless_dry "Removed the mise wrapper: $command"
}

# --- teeup install dev-env ---------------------------------------------------

TEEUP_DEV_ENVS="python node java ruby rust go"

# dev_env_install <python|node|java|ruby|rust|go>
# Runtimes get no shims (spec section 4a: macOS ships python3, ruby and java,
# so a PATH-last shim could never fire) and arrive only through this command.
# Everything is `mise use --global`; Python brings uv along; Rust goes
# through mise's rust backend, which drives rustup (installing it into
# ~/.rustup and ~/.cargo when no rustup is on PATH), so the same call works
# on a Homebrew and on a MacPorts machine.
dev_env_install() {
  local lang="${1:-}" l known=false
  for l in $TEEUP_DEV_ENVS; do
    if [[ "$l" == "$lang" ]]; then known=true; fi
  done
  if [[ "$known" != "true" ]]; then
    err "Usage: teeup install dev-env <python|node|java|ruby|rust|go>"
    return 1
  fi
  if ! have mise; then
    err "mise is not installed; run: teeup install mise"
    return 1
  fi
  case "$lang" in
    python)
      mise_ensure_global python latest || return 1
      mise_ensure_global uv latest || return 1
      ;;
    node) mise_ensure_global node latest || return 1 ;;
    java)
      mise_ensure_global java latest || return 1
      # javav (capabilities/zsh/default/functions) only exists once the zsh
      # capability has installed it; naming it unconditionally would send a
      # bash user, or anyone who skipped zsh, to a command that is not there
      # (M4, same class as I4).
      if state_done check "cap-zsh"; then
        log "Switch Java per shell with: javav 21 (Corretto 21), javav zulu-17, javav (show)"
      else
        log "Switch Java per shell with: mise use java@<spec> (install teeup's zsh layer for the javav shortcut: teeup install zsh)"
      fi
      ;;
    ruby) mise_ensure_global ruby latest || return 1 ;;
    rust) mise_ensure_global rust latest || return 1 ;;
    go) mise_ensure_global go latest || return 1 ;;
  esac
  state_done mark "dev-env-$lang"
  # "the next prompt in this shell has it (mise activate)" is only true once
  # the zsh capability's `mise activate` is actually loaded (M4): on a bash
  # session, or a Mac that skipped zsh, nothing here reruns automatically.
  if state_done check "cap-zsh"; then
    ok_unless_dry "$lang is ready: the next prompt in this shell has it (mise activate); other shells after a new terminal."
  else
    ok_unless_dry "$lang is ready through mise. Install teeup's zsh layer (teeup install zsh) so new shells pick it up automatically; for now use: mise x $lang -- ..., or mise use $lang in this shell."
  fi
}

# dev_env_installed -> the dev-envs this machine has marked, one per line.
dev_env_installed() {
  local l
  for l in $TEEUP_DEV_ENVS; do
    state_done check "dev-env-$l" && printf '%s\n' "$l"
  done
  return 0
}

# mise_upgrade
# `teeup update`'s mise step (spec section 9): upgrade every tool the global
# config holds, which is the AI CLIs' tools, the dev-env runtimes and anything
# else installed with `mise use -g`. `-C /` keeps it to that config, the rule
# every mise call outside a wrapper follows. A machine without mise is not an
# error: mise is a core capability, but `teeup update` also runs on a machine
# where it is in TEEUP_SKIP.
mise_upgrade() {
  if ! have mise; then
    log "mise is not installed here; skipping the mise upgrade."
    return 0
  fi
  run_cmd mise -C / upgrade || { warn "mise upgrade returned non-zero."; return 1; }
}

# --- user tools pinned by the release (#112) ---------------------------------
# The tools the user uses come from mise at the exact versions in
# share/teeup/tools.lock; what teeup itself needs stays with the package
# manager. A test points TEEUP_TOOLS_LOCK at a fixture.

TEEUP_TOOLS_LOCK="${TEEUP_TOOLS_LOCK:-$TEEUP_PATH/share/teeup/tools.lock}"

# tools_lock_version <tool> -> the version the lock pins; 1 when the lock is
# unreadable or names no such tool. Comment lines never match.
tools_lock_version() {
  local tool="$1" version
  [[ -r "$TEEUP_TOOLS_LOCK" ]] || return 1
  version="$(awk -v t="$tool" '$1 !~ /^#/ && $1 == t { print $2; exit }' "$TEEUP_TOOLS_LOCK")"
  if [[ -z "$version" ]]; then
    return 1
  fi
  printf '%s\n' "$version"
}

# tools_lock_spec <tool> -> what mise is given for <tool>: the lock's third
# field when it names a backend (neovim's registry entry lists vfox first,
# and the release wants the aqua build), else the tool name itself.
tools_lock_spec() {
  local tool="$1" spec
  [[ -r "$TEEUP_TOOLS_LOCK" ]] || return 1
  spec="$(awk -v t="$tool" '$1 !~ /^#/ && $1 == t { print ($3 != "" ? $3 : $1); exit }' "$TEEUP_TOOLS_LOCK")"
  if [[ -z "$spec" ]]; then
    return 1
  fi
  printf '%s\n' "$spec"
}

# The first line of conf.d/teeup.toml: the record that teeup wrote it.
TEEUP_MISE_CONF_MARKER="# teeup mise tools; regenerated by: teeup configure <capability> and teeup update"

# _mise_tools_conf_version <spec> [content]
# -> the version conf.d/teeup.toml currently pins for <spec> (a line reads
# "<spec>" = "<version>", one per mise_tools_conf_write): mise_tools_conf_write's
# own carry-forward for a version that failed to install, and mise_tool_remove's
# way to find the version teeup actually linked when the lock has since moved.
# <content> is the file's text when a caller already has it (the carry-forward,
# which read it once as "old" before this call's rewrite); without it, the
# file on disk is read fresh. Empty when there is no such line, or no file.
_mise_tools_conf_version() {
  local spec="$1" content
  if [[ $# -ge 2 ]]; then
    content="$2"
  else
    content="$(cat "$(mise_tools_conf_file)" 2>/dev/null || true)"
  fi
  printf '%s\n' "$content" | awk -v k="\"$spec\" = \"" '
    index($0, k) == 1 {
      v = substr($0, length(k) + 1)
      sub(/"$/, "", v)
      print v
      exit
    }'
}

# mise_tools_conf_file -> where teeup pins its tools for mise. mise reads
# every conf.d/*.toml in its config directory as part of the global config,
# and MISE_CONFIG_DIR moves that directory as it moves config.toml.
mise_tools_conf_file() {
  printf '%s/conf.d/teeup.toml\n' "${MISE_CONFIG_DIR:-$(user_config_dir)/mise}"
}

# mise_tools_conf_write [--with <capability>] [--without <capability>]
# Writes conf.d/teeup.toml from the lock: one [tools] entry for each mise
# tool of each capability marked installed (TEEUP_SKIP or not: a capability
# skipped after its install still has its links, and an unpinned version is
# one `mise prune` removes). Only an installed version is pinned (Decision
# 5): a pin for a missing version makes `mise activate` warn in every shell.
# When the lock's version is not installed (its download failed, or sync
# skipped the capability), the tool keeps the line it has in the current
# file, or is left out when it has none. A TEEUP_SKIP'd capability's tool
# always keeps its current line when it has one, and only without one
# follows the rule above. Without mise on PATH, or in a dry run, the lock's
# version is pinned as it is. --with counts a capability
# whose install or configure is running before its done marker exists;
# --without leaves out one being removed. The user's config.toml is never
# edited. With nothing to pin, teeup's file is deleted. A file without the
# marker is not teeup's and is left alone. When MISE_GLOBAL_CONFIG_FILE is
# set, mise reads only that file as its global config and never looks at
# conf.d at all, so this file is written exactly as it would be without the
# variable (teeup does not edit the user's file for them), and a warning
# says so once rather than once per tool.
# 0 written, already current or removed; 1 refused.
mise_tools_conf_write() {
  local with="" without="" file name pair tool version spec body="" old="" old_version check=false
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --with|--without)
        if [[ $# -lt 2 || -z "$2" ]]; then
          err "mise_tools_conf_write: $1 needs a capability name"
          return 1
        fi
        if [[ "$1" == "--with" ]]; then with="$2"; else without="$2"; fi
        shift 2
        ;;
      *) err "mise_tools_conf_write: unknown argument '$1'"; return 1 ;;
    esac
  done
  file="$(mise_tools_conf_file)"
  if [[ -e "$file" || -L "$file" ]] && ! head -1 "$file" 2>/dev/null | grep -qxF "$TEEUP_MISE_CONF_MARKER"; then
    warn "Keeping $file: it was not written by teeup, so the versions teeup pins are in no mise config and mise prune can remove them. Move it aside, then run: teeup update"
    return 1
  fi
  if [[ -f "$file" ]]; then
    old="$(cat "$file")"
  fi
  if [[ "$DRY_RUN" != "true" ]] && have mise; then
    check=true
  fi
  for name in $(cap_list); do
    if [[ "$name" == "$without" ]]; then continue; fi
    if [[ "$name" != "$with" ]] && ! state_done check "cap-$name"; then continue; fi
    for pair in $(cap_meta_get "$name" mise_tools); do
      tool="${pair%%:*}"
      if ! version="$(tools_lock_version "$tool")"; then
        warn "$name names $tool in mise_tools, but $TEEUP_TOOLS_LOCK has no line for it, so $file leaves it out."
        continue
      fi
      spec="$(tools_lock_spec "$tool")"
      # A skipped capability is not teeup's to move: its line stays as it
      # is, even when the lock's new version is on disk for another reason.
      if cap_skipped "$name"; then
        old_version="$(_mise_tools_conf_version "$spec" "$old")"
        if [[ -n "$old_version" ]]; then
          body="$body\"$spec\" = \"$old_version\""$'\n'
          continue
        fi
      fi
      if [[ "$check" == "true" ]] && ! mise -C / where "$spec@$version" >/dev/null 2>&1; then
        old_version="$(_mise_tools_conf_version "$spec" "$old")"
        if [[ -n "$old_version" ]]; then
          body="$body\"$spec\" = \"$old_version\""$'\n'
        fi
        continue
      fi
      body="$body\"$spec\" = \"$version\""$'\n'
    done
  done
  if [[ -z "$body" ]]; then
    if [[ -e "$file" ]]; then
      if ! run_cmd rm -f "$file"; then
        warn "Could not remove $file. Remove it by hand."
        return 1
      fi
      ok_unless_dry "Removed $file: no capability here uses a tool from mise any more."
    fi
    return 0
  fi
  if [[ -n "${MISE_GLOBAL_CONFIG_FILE:-}" ]]; then
    warn "MISE_GLOBAL_CONFIG_FILE is set, so mise does not read $file; mise prune can remove teeup's pinned tools. Unset it, or add these versions to $MISE_GLOBAL_CONFIG_FILE yourself."
  fi
  printf '%s\n%s\n[tools]\n%s' "$TEEUP_MISE_CONF_MARKER" \
    "# The versions come from share/teeup/tools.lock in the teeup checkout." "$body" |
    write_managed_file "$file" "the tool versions teeup pins for mise"
}

# The second line of a script teeup writes in place of a link (below).
TEEUP_MISE_TOOL_MARKER="# teeup mise tool; regenerated by: teeup configure"

# Tools whose command must be a script that execs the binary rather than a
# symlink: a tool that finds its own files next to the path it was started
# as would look for them in ~/.local/bin. Empty until the spec's Mac
# verification names one; adding the tool here is the whole change. bash
# startup for the script costs about 1 ms.
TEEUP_MISE_EXEC_SCRIPT_TOOLS="${TEEUP_MISE_EXEC_SCRIPT_TOOLS:-}"

# mise_installs_dir -> where mise keeps installed versions, resolved the way
# mise resolves its data root.
mise_installs_dir() {
  printf '%s/installs\n' "${MISE_DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/mise}"
}

# local_bin_on_path: puts ~/.local/bin first on PATH for this process, as
# capabilities/zsh/default/env does for every shell. bin/teeup and bootstrap
# call it so a capability script sees the links mise_tool_install writes
# even from a Terminal the shell layer has not set up yet. An entry further
# down is moved to the front rather than kept, because pkg_backend_path
# prepends the package manager's directories and is called again later (by
# cmd_lazy_run and mise_tools_apply), each time followed by this.
local_bin_on_path() {
  local dir="$HOME/.local/bin" rest entry others=""
  case "$PATH" in
    "$dir"|"$dir":*) return 0 ;;
  esac
  if [[ -z "$PATH" ]]; then
    PATH="$dir"; export PATH
    return 0
  fi
  rest="$PATH:"
  while [[ -n "$rest" ]]; do
    entry="${rest%%:*}"
    rest="${rest#*:}"
    if [[ "$entry" != "$dir" ]]; then
      others="$others:$entry"
    fi
  done
  PATH="$dir$others"; export PATH
}

# _mise_plain_names <caller> <name...>: every name is a plain tool or
# command name, or an error names the caller and the name.
_mise_plain_names() {
  local caller="$1" t
  shift
  for t in "$@"; do
    if ! [[ "$t" =~ ^[A-Za-z0-9][A-Za-z0-9_.+-]*$ ]]; then
      err "$caller: '$t' is not a plain tool or command name"
      return 1
    fi
  done
}

# _mise_tool_wants_script <tool> -> 0 when <tool> is in
# TEEUP_MISE_EXEC_SCRIPT_TOOLS.
_mise_tool_wants_script() {
  case " $TEEUP_MISE_EXEC_SCRIPT_TOOLS " in
    *" $1 "*) return 0 ;;
  esac
  return 1
}

# _mise_tool_script <bin> -> the exec script for <bin>, single-quoted for sh.
_mise_tool_script() {
  local quoted
  quoted="$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
  printf '#!/bin/sh\n%s\nexec '\''%s'\'' "$@"\n' "$TEEUP_MISE_TOOL_MARKER" "$quoted"
}

# teeup's own directory for its mise tools: one entry per command, a
# symlink to the pinned binary (or, for a tool in
# TEEUP_MISE_EXEC_SCRIPT_TOOLS, the exec script above). Only teeup writes
# here. ~/.local/bin/<command> is a symlink to the entry, so who owns the
# ~/.local/bin path is a fact on disk: it is teeup's exactly when it points
# here. A symlink straight into mise's installs directory says nothing about
# who made it (a user's `mise use -g` setup can make the same one), so it is
# the user's. That also covers such a link from before the two-hop layout:
# that layout never shipped in a release, so no migration takes it over.
TEEUP_MISE_TOOLS_DIR="${TEEUP_MISE_TOOLS_DIR:-$TEEUP_STATE_DIR/tools}"

# _mise_tool_inner <command> -> teeup's own entry for <command>.
_mise_tool_inner() {
  printf '%s/%s\n' "$TEEUP_MISE_TOOLS_DIR" "$1"
}

# mise_tool_link_owned <path> -> 0 when <path> (~/.local/bin/<command>) is
# teeup's: a symlink whose target is exactly teeup's own entry for
# <command>, dangling or not. Anything else at the path is the user's.
mise_tool_link_owned() {
  local path="$1"
  [[ -L "$path" && "$(readlink "$path")" == "$(_mise_tool_inner "${path##*/}")" ]]
}

# mise_tool_used <command> -> 0 when teeup uses the tool behind <command>:
# ~/.local/bin/<command> is teeup's link, or it is missing and teeup's own
# entry still exists (the user deleted the link; a retry after a failed
# uninstall). Anything else at the ~/.local/bin path makes the tool the
# user's, even with an entry of teeup's left over. This, not a record,
# decides whether `teeup remove --packages` may uninstall the version.
mise_tool_used() {
  local inner link="$HOME/.local/bin/$1"
  if [[ -e "$link" || -L "$link" ]] && ! mise_tool_link_owned "$link"; then
    return 1
  fi
  inner="$(_mise_tool_inner "$1")"
  if [[ -e "$inner" || -L "$inner" ]]; then
    return 0
  fi
  mise_tool_link_owned "$HOME/.local/bin/$1"
}

# mise_tool_versions <tool> -> the version(s) of <tool> teeup uses, one per
# line: the version conf.d/teeup.toml pins, then the lock's when it differs.
# They differ when a bumped pin's download failed and the old pin was
# carried forward (mise_tools_conf_write). Without a conf.d line, the lock's
# version alone. Fails when the lock has no line for <tool>. A caller checks
# which of them mise actually has installed.
mise_tool_versions() {
  local tool="$1" version spec conf_version
  version="$(tools_lock_version "$tool")" || return 1
  spec="$(tools_lock_spec "$tool")"
  conf_version="$(_mise_tools_conf_version "$spec")"
  if [[ -n "$conf_version" && "$conf_version" != "$version" ]]; then
    printf '%s\n' "$conf_version"
  fi
  printf '%s\n' "$version"
}

# _mise_tool_inner_remove <command>: deletes teeup's own entry for
# <command>, and teeup's directory once it is empty. A dry run only says so.
_mise_tool_inner_remove() {
  local inner
  inner="$(_mise_tool_inner "$1")"
  if [[ ! -e "$inner" && ! -L "$inner" ]]; then
    return 0
  fi
  if ! run_cmd rm -f "$inner"; then
    warn "Could not remove $inner. Fix its permissions and try again."
    return 1
  fi
  if [[ "$DRY_RUN" != "true" ]]; then
    rmdir "$TEEUP_MISE_TOOLS_DIR" 2>/dev/null || true
  fi
}

# mise_tool_link_is <path> <bin> -> 0 when <path> (teeup's own entry for a
# command) already runs <bin>.
mise_tool_link_is() {
  local path="$1" bin="$2"
  if [[ -L "$path" ]]; then
    if [[ "$(readlink "$path")" == "$bin" ]]; then return 0; fi
    return 1
  fi
  if [[ -f "$path" && "$(cat "$path")" == "$(_mise_tool_script "$bin")" ]]; then
    return 0
  fi
  return 1
}

# mise_tool_install <tool> <command>
# Installs <tool> at the version share/teeup/tools.lock pins (only when that
# version is not installed yet), asks mise where its <command> is, points
# teeup's own entry for <command> at it, and links ~/.local/bin/<command> to
# that entry. A call then runs the binary directly, with no mise process in
# between. A lock bump re-points only the entry. A file or link at the
# ~/.local/bin path that is not teeup's is kept, with a warning, as
# mise_wrapper_write does; no entry is made for it, and a stale one is
# dropped. The previous version
# stays installed; `mise prune` removes it once nothing pins it.
# TEEUP_CAP names the capability in the repair hints when it is set.
# 0 linked, already linked, kept, or previewed; 1 <command> is missing.
mise_tool_install() {
  local tool="$1" command="$2" version spec link inner bin owner
  _mise_plain_names mise_tool_install "$tool" "$command" || return 1
  if ! version="$(tools_lock_version "$tool")"; then
    err "mise_tool_install: $tool has no line in $TEEUP_TOOLS_LOCK"
    return 1
  fi
  spec="$(tools_lock_spec "$tool")"
  link="$HOME/.local/bin/$command"
  inner="$(_mise_tool_inner "$command")"
  owner="${TEEUP_CAP:-<capability>}"
  if [[ -e "$link" || -L "$link" ]] && ! mise_tool_link_owned "$link"; then
    warn "Keeping $link: it was not written by teeup, so $command is not the pinned $tool $version. Remove it, then run: teeup configure $owner"
    # An entry teeup made before the user put their own file there is stale.
    _mise_tool_inner_remove "$command" || true
    return 0
  fi
  if ! have mise; then
    if [[ "$DRY_RUN" == "true" ]]; then
      run_cmd mise -C / install "$spec@$version"
      printf "%b %s\n" "🔍" "[DRY-RUN] Would link $link to $tool $version (mise)"
      return 0
    fi
    warn "mise is not on PATH, so $tool $version was not installed and $command is missing. Run: teeup install mise, then: teeup configure $owner"
    return 1
  fi
  if ! mise -C / where "$spec@$version" >/dev/null 2>&1; then
    if ! run_cmd mise -C / install "$spec@$version"; then
      warn "mise could not install $tool $version, so $command is missing. Fix the cause above, then run: teeup configure $owner"
      return 1
    fi
    if [[ "$DRY_RUN" == "true" ]]; then
      printf "%b %s\n" "🔍" "[DRY-RUN] Would link $link to $tool $version (mise)"
      return 0
    fi
  fi
  if ! bin="$(mise -C / which --tool "$spec@$version" "$command" 2>/dev/null)" || [[ -z "$bin" || ! -x "$bin" ]]; then
    warn "mise installed $tool $version, but it has no $command, so $link was not written."
    return 1
  fi
  if mise_tool_link_is "$inner" "$bin" && mise_tool_link_owned "$link"; then
    log "Already linked: $command ($tool $version)"
    return 0
  fi
  if ! mise_tool_link_is "$inner" "$bin"; then
    if [[ ! -d "$TEEUP_MISE_TOOLS_DIR" ]]; then
      run_cmd mkdir -p "$TEEUP_MISE_TOOLS_DIR" || return 1
    fi
    if _mise_tool_wants_script "$tool"; then
      # write_managed_file refuses to write through a symlink.
      if [[ -L "$inner" ]]; then
        run_cmd rm -f "$inner" || return 1
      fi
      _mise_tool_script "$bin" | write_managed_file "$inner" "$command, which runs $tool $version" || return 1
      if [[ "$DRY_RUN" != "true" ]]; then
        chmod 755 "$inner"
      fi
    elif ! run_cmd ln -sfn "$bin" "$inner"; then
      warn "Could not link $inner to $bin. Fix the permissions of $TEEUP_MISE_TOOLS_DIR, then run: teeup configure $owner"
      return 1
    fi
  fi
  if ! mise_tool_link_owned "$link"; then
    if [[ ! -d "$HOME/.local/bin" ]]; then
      run_cmd mkdir -p "$HOME/.local/bin" || return 1
    fi
    if ! run_cmd ln -sfn "$inner" "$link"; then
      warn "Could not link $link to $inner. Fix the permissions of $HOME/.local/bin, then run: teeup configure $owner"
      return 1
    fi
  fi
  ok_unless_dry "Linked $command to $tool $version (mise)"
}

# mise_tool_remove <tool> <command> [true|false]
# Removes ~/.local/bin/<command> when it is teeup's link; a foreign file or
# link stays, with a warning. Without packages, teeup's own entry for
# <command> goes too. With true (`teeup remove`, `teeup uninstall
# --packages`) it also uninstalls the version(s) teeup uses
# (mise_tool_versions) that mise has installed, and deletes the entry only
# after that worked: on a failure the entry stays, so a retry still knows
# teeup used the tool. `mise uninstall` never runs for a tool teeup does not
# use (mise_tool_used): with a foreign file at the path, the version is not
# teeup's to take away, and a leftover entry of teeup's is dropped. The conf.d file is
# the caller's to rewrite (cap_remove does it once per capability).
# 0 removed or nothing to do; 1 something that should be gone is still there.
mise_tool_remove() {
  local tool="$1" command="$2" with_packages="${3:-false}" link version spec v rc=0 used=false
  _mise_plain_names mise_tool_remove "$tool" "$command" || return 1
  link="$HOME/.local/bin/$command"
  # Asked before the link goes: an owned link is one way teeup used it.
  if mise_tool_used "$command"; then
    used=true
  fi
  if [[ -e "$link" || -L "$link" ]]; then
    if mise_tool_link_owned "$link"; then
      if ! run_cmd rm -f "$link"; then
        warn "Could not remove $link. Fix its permissions and try again."
        return 1
      fi
      if [[ "$DRY_RUN" != "true" && ( -e "$link" || -L "$link" ) ]]; then
        warn "$link is still there. Remove it and try again."
        return 1
      fi
      ok_unless_dry "Removed the link: $command"
    else
      warn "Keeping $link: it was not written by teeup."
    fi
  fi
  if [[ "$with_packages" != "true" ]]; then
    _mise_tool_inner_remove "$command"
    return $?
  fi
  if ! version="$(tools_lock_version "$tool")"; then
    log "$TEEUP_TOOLS_LOCK has no line for $tool, so no pinned version of it is uninstalled."
    _mise_tool_inner_remove "$command"
    return $?
  fi
  if [[ "$used" != "true" ]]; then
    log "Keeping $tool $version: teeup did not link $command, so it leaves the version installed."
    _mise_tool_inner_remove "$command"
    return $?
  fi
  spec="$(tools_lock_spec "$tool")"
  if ! have mise; then
    if [[ "$DRY_RUN" == "true" ]]; then
      for v in $(mise_tool_versions "$tool"); do
        run_cmd mise -C / uninstall "$spec@$v"
      done
      _mise_tool_inner_remove "$command"
      return $?
    fi
    warn "mise is not on PATH, so $tool $version stays installed. Once mise is back, run: mise uninstall $spec@$version"
    return 1
  fi
  for v in $(mise_tool_versions "$tool"); do
    if ! mise -C / where "$spec@$v" >/dev/null 2>&1; then
      log "Not installed through mise, so nothing to uninstall: $tool $v"
      continue
    fi
    if ! run_cmd mise -C / uninstall "$spec@$v"; then
      warn "Could not uninstall $tool $v through mise. Run: mise uninstall $spec@$v"
      rc=1
      continue
    fi
    ok_unless_dry "Uninstalled $tool $v (mise)"
  done
  if [[ $rc -ne 0 ]]; then
    return $rc
  fi
  _mise_tool_inner_remove "$command"
}

# mise_tools_apply <capability>
# What a capability's install runs for its mise_tools pairs: install and
# link each one, then rewrite conf.d with this capability counted as
# installed. Installing first lets mise_tools_conf_write see which versions
# are on disk: one that failed to download is never pinned, so `mise
# activate` does not warn about it in every shell. A
# mise the package manager installed earlier in this run is found even
# before the shell layer puts its prefix on PATH.
# 0 every tool linked; 1 otherwise (the warnings say which).
mise_tools_apply() {
  local cap="$1" pair cmds="" rc=0
  for pair in $(cap_meta_get "$cap" mise_tools); do
    cmds="${cmds:+$cmds }${pair#*:}"
  done
  if [[ -z "$cmds" ]]; then
    return 0
  fi
  if cap_skipped mise; then
    warn "mise is skipped on this machine (TEEUP_SKIP), so teeup does not install $cmds for $cap. Install them another way, or take mise out of TEEUP_SKIP."
    return 1
  fi
  pkg_backend_path
  local_bin_on_path
  for pair in $(cap_meta_get "$cap" mise_tools); do
    if ! TEEUP_CAP="$cap" mise_tool_install "${pair%%:*}" "${pair#*:}"; then
      rc=1
    fi
  done
  if ! mise_tools_conf_write --with "$cap"; then
    rc=1
  fi
  return $rc
}

# mise_tools_repair <capability>
# What a capability's configure runs: `teeup configure <cap>` is the repair
# path for a missing pinned version or a broken link. A failure is a warning,
# so the rest of configure still runs. Silent when mise is skipped: install
# already said so.
mise_tools_repair() {
  local cap="$1"
  if cap_skipped mise; then
    return 0
  fi
  if ! mise_tools_apply "$cap"; then
    warn "Some of $cap's tools from mise are missing or not linked (the lines above say why). Fix that, then run: teeup configure $cap"
  fi
  return 0
}

# mise_tools_sync
# `teeup update`'s pinned-tools step and the migration's whole job: every
# installed, unskipped capability's tools installed and linked at the
# versions the lock names now, lazy capabilities included (update never runs
# their configure). A tool whose pin changed gets the new version; the old
# one stays for `mise prune`. conf.d is rewritten last.
# 0 everything linked or nothing to do; 1 otherwise.
mise_tools_sync() {
  local name pair rc=0 any=false
  if cap_skipped mise; then
    log "mise is skipped on this machine (TEEUP_SKIP), so the tools teeup pins are left as they are."
    return 0
  fi
  for name in $(cap_list); do
    if state_done check "cap-$name" && ! cap_skipped "$name" && [[ -n "$(cap_meta_get "$name" mise_tools)" ]]; then
      any=true
    fi
  done
  if [[ "$any" != "true" ]]; then
    mise_tools_conf_write
    return $?
  fi
  pkg_backend_path
  local_bin_on_path
  if [[ "$DRY_RUN" != "true" ]] && ! have mise; then
    warn "mise is not on PATH, so the tools teeup pins were not checked. Run: teeup install mise, then: teeup update"
    return 1
  fi
  for name in $(cap_list); do
    if ! state_done check "cap-$name"; then continue; fi
    if cap_skipped "$name"; then
      log "Skipping $name's tools from mise (TEEUP_SKIP)"
      continue
    fi
    for pair in $(cap_meta_get "$name" mise_tools); do
      if ! TEEUP_CAP="$name" mise_tool_install "${pair%%:*}" "${pair#*:}"; then
        rc=1
      fi
    done
  done
  if ! mise_tools_conf_write; then
    rc=1
  fi
  return $rc
}

# mise_tool_old_packages <tool> -> the package names this backend knew
# <tool> by when teeup 0.3.0-beta and older installed it there, for doctor's
# old-copy notice. Homebrew's tldr formula and MacPorts' tealdeer port both
# gave the `tldr` command; git-delta gave `delta` on both.
mise_tool_old_packages() {
  case "$(pkg_backend):$1" in
    homebrew:delta|macports:delta) echo "git-delta" ;;
    homebrew:tealdeer) echo "tldr tealdeer" ;;
    *) echo "$1" ;;
  esac
}

# mise_tool_old_package_uninstall <pkg> -> the command that removes <pkg>.
mise_tool_old_package_uninstall() {
  case "$(pkg_backend)" in
    homebrew) printf 'brew uninstall %s\n' "$1" ;;
    macports) printf 'sudo port uninstall %s\n' "$1" ;;
  esac
}
