#!/usr/bin/env bash
# mise.sh - mise-managed tools: the global-state check every mise consumer
# needs, the on-first-call wrappers for AI CLIs, and `teeup install dev-env`.
# Requires core.sh, files.sh, state.sh and pkg.sh.
#
# Every mise call here runs with `-C /` ("Change directory before running
# command") except the `mise x` line inside a wrapper, which must run in the
# caller's directory. mise resolves its configuration stack from the current
# directory, so run from inside a project whose own mise.toml also asks for
# the tool, `mise ls --global` hides the global row entirely (verified on
# 2026.9.4: the project's request shadows the global one), `mise install`
# resolves the project's version and `mise where` reports the project's
# install. From `/` no project config is in reach and the global config
# (MISE_CONFIG_DIR or ~/.config/mise, unaffected by -C) is the whole stack.

# mise_global_state <tool> -> installed | requested | absent
# Two questions, because mise answers them separately. `mise ls --global`
# ("Only show tool versions currently specified in the global mise.toml")
# says whether the global config *requests* the tool, but it lists requested
# versions whether or not they are installed, so a row there is no proof of a
# binary: an interrupted install, a manual uninstall or a wiped MISE_DATA_DIR
# all leave the request behind with the tool gone. `--installed` ("Hides
# tools defined in mise.toml but not installed") answers the second question;
# with both flags and the tool name, a row comes back only when the tool is
# requested globally and on disk. A mise that rejects --installed gets
# `mise where <tool>` instead, which fails when the requested version is not
# installed. A mise too old for --global exits non-zero on it; there, the
# global config file (the same file `mise use -g` writes) answers the first
# question and `mise where` the second.
mise_global_state() {
  local tool="$1" config_file rows
  config_file="${MISE_CONFIG_DIR:-$(user_config_dir)/mise}/config.toml"
  if rows="$(mise -C / ls --global 2>/dev/null)"; then
    if printf '%s\n' "$rows" | awk '{print $1}' | grep -qx "$tool"; then
      if rows="$(mise -C / ls --global --installed "$tool" 2>/dev/null)"; then
        if printf '%s\n' "$rows" | awk '{print $1}' | grep -qx "$tool"; then
          echo installed
          return 0
        fi
      elif mise -C / where "$tool" >/dev/null 2>&1; then
        echo installed
        return 0
      fi
      echo requested
      return 0
    fi
  elif [[ -f "$config_file" ]]; then
    if grep -qE "^[[:space:]]*(\"$tool\"|$tool)[[:space:]]*=" "$config_file"; then
      if mise -C / where "$tool" >/dev/null 2>&1; then echo installed; else echo requested; fi
      return 0
    fi
  fi
  echo absent
}

# mise_ensure_global <tool> [version]
#   requested and installed  -> nothing to do
#   requested but missing    -> `mise install` (honours the pinned version;
#                               `mise use -g` would rewrite the request)
#   not requested            -> `mise use -g` (writes the request and installs)
# Warns and returns 1 when mise cannot install it, so a caller under `set -e`
# decides whether that is fatal.
mise_ensure_global() {
  local tool="$1" version="${2:-}"
  case "$(mise_global_state "$tool")" in
    installed)
      log "Already installed through mise: $tool"
      ;;
    requested)
      log "$tool is requested by the global mise config but not installed; installing it."
      run_cmd mise -C / install "$tool" || { warn "Could not install $tool through mise."; return 1; }
      ;;
    *)
      run_cmd mise -C / use -g "$tool${version:+@$version}" || { warn "Could not install $tool through mise."; return 1; }
      ;;
  esac
}

# The second line of every wrapper teeup writes. mise_wrapper_write replaces
# only files that carry it, so a `claude` some other installer put in
# ~/.local/bin (Claude Code's native installer manages ~/.local/bin/claude as
# a symlink) is left alone with a warning instead of being overwritten.
TEEUP_MISE_WRAPPER_MARKER="# teeup mise wrapper; regenerated by: teeup configure ai"

# mise_wrapper_write <command> <tool> [runtime...]
# Omarchy's omarchy-mise-install pattern: ~/.local/bin/<command> installs
# <tool> through mise on its first call and execs it through `mise x` after
# that, so `mise upgrade` keeps it current and nothing is downloaded at
# configure time. `mise where` exits non-zero until a tool is installed, so a
# later call costs one `mise where` per tool and never rewrites a version the
# user pinned in the global config. A runtime is a tool the command needs at
# run time that mise will not bring along (the npm backend installs a package
# without Node, but the package still runs on Node); it is installed first and
# loaded into the same `mise x`. MISE_MINIMUM_RELEASE_AGE=0 lifts mise's
# release cooldown for these self-updating tools and is exported, as Omarchy
# does, so the version `mise x` resolves agrees with the one just installed.
# Every call is `mise -C /` except `mise x`, which must run the command in the
# caller's directory (verified: `mise -C / x uv -- pwd` prints `/`).
mise_wrapper_write() {
  local command="$1" tool="$2" file t tools
  shift 2
  tools="$* $tool"
  tools="${tools# }"
  for t in "$command" $tools; do
    if ! [[ "$t" =~ ^[A-Za-z0-9][A-Za-z0-9_.+-]*$ ]]; then
      err "mise_wrapper_write: '$t' is not a plain command or tool name"
      return 1
    fi
  done
  file="$HOME/.local/bin/$command"
  if [[ -e "$file" || -L "$file" ]] && ! sed -n 2p "$file" 2>/dev/null | grep -qxF "$TEEUP_MISE_WRAPPER_MARKER"; then
    warn "Keeping $file: it was not written by teeup. Remove it and run teeup configure ai to use the mise wrapper."
    return 0
  fi
  [[ -d "$HOME/.local/bin" ]] || run_cmd mkdir -p "$HOME/.local/bin"
  write_managed_file "$file" "mise wrapper for $command" <<WRAPPER
#!/bin/bash
$TEEUP_MISE_WRAPPER_MARKER
# Installs $tools through mise on the first call, then runs $command.
export MISE_MINIMUM_RELEASE_AGE=0
for teeup_tool in $tools; do
  mise -C / where "\$teeup_tool" >/dev/null 2>&1 || mise -C / use -g --quiet "\$teeup_tool" || exit 1
done
exec mise x $tools -- $command "\$@"
WRAPPER
  [[ "$DRY_RUN" == "true" ]] || chmod 755 "$file"
}

# --- teeup install dev-env ---------------------------------------------------

TEEUP_DEV_ENVS="python node java ruby rust go"

# dev_env_install <python|node|java|ruby|rust|go>
# Runtimes get no shims (spec section 4a: macOS ships python3, ruby and java,
# so a PATH-last shim could never fire) and arrive only through this command.
# Everything is `mise use --global`; Python brings uv along; Rust goes
# through mise's rust backend, which drives rustup (installing it into
# ~/.rustup and ~/.cargo when no rustup is on PATH), so the same call works
# on a Homebrew and on a MacPorts machine.
dev_env_install() {
  local lang="${1:-}" l known=false
  for l in $TEEUP_DEV_ENVS; do
    if [[ "$l" == "$lang" ]]; then known=true; fi
  done
  if [[ "$known" != "true" ]]; then
    err "Usage: teeup install dev-env <python|node|java|ruby|rust|go>"
    return 1
  fi
  if ! have mise; then
    err "mise is not installed; run: teeup install mise"
    return 1
  fi
  case "$lang" in
    python)
      mise_ensure_global python latest || return 1
      mise_ensure_global uv latest || return 1
      ;;
    node) mise_ensure_global node latest || return 1 ;;
    java)
      mise_ensure_global java latest || return 1
      log "Switch Java per shell with: javav 21 (Corretto 21), javav zulu-17, javav (show)"
      ;;
    ruby) mise_ensure_global ruby latest || return 1 ;;
    rust) mise_ensure_global rust latest || return 1 ;;
    go) mise_ensure_global go latest || return 1 ;;
  esac
  state_done mark "dev-env-$lang"
  ok_unless_dry "$lang is ready: the next prompt in this shell has it (mise activate); other shells after a new terminal."
}

# dev_env_installed -> the dev-envs this machine has marked, one per line.
dev_env_installed() {
  local l
  for l in $TEEUP_DEV_ENVS; do
    state_done check "dev-env-$l" && printf '%s\n' "$l"
  done
  return 0
}
