-- Generated by `teeup theme set`. Do not edit; the next theme switch replaces
-- it. Read by capabilities/neovim/default/teeup/neovim.lua for the {{ mode }}
-- appearance: the colorscheme to load, and the palette for your own
-- highlights (require("teeup.neovim").theme().colors.accent).
return {
  mode = "{{ mode }}",
  colorscheme = "{{ neovim_colorscheme }}",
  colors = {
    accent = "{{ accent }}",
    selection = "{{ selection }}",
    muted = "{{ muted }}",
    background = "{{ background }}",
    dark_background = "{{ dark_background }}",
    lighter_background = "{{ lighter_background }}",
    foreground = "{{ foreground }}",
    light_foreground = "{{ light_foreground }}",
    bright_foreground = "{{ bright_foreground }}",
    red = "{{ red }}",
    orange = "{{ orange }}",
    yellow = "{{ yellow }}",
    green = "{{ green }}",
    cyan = "{{ cyan }}",
    blue = "{{ blue }}",
    magenta = "{{ magenta }}",
  },
}
