;;; doom-theme.el --- generated by `teeup theme set'; do not edit  -*- lexical-binding: t -*-
;; The next theme switch replaces this file. Doom reads `doom-theme' from its
;; own config.el, never from capabilities/emacs/default/teeup/init.el (Doom
;; does not load that starter layer), so this file plays the starter's role
;; for the {{ mode }} appearance: capabilities/emacs/configure adds one marked
;; line to Doom's config.el that loads whichever mode's copy of this file
;; matches the machine's current appearance. `teeup-apply' is what the daemon
;; hook (capabilities/emacs/theme-apply) calls after `teeup theme set'; the
;; starter and Spacemacs never define it, so the call is a no-op there.
(setq doom-theme (intern "{{ doom_theme }}"))

(defun teeup-apply ()
  "Reload the Doom theme teeup set."
  (interactive)
  (mapc #'disable-theme custom-enabled-themes)
  (load-theme doom-theme t))
