;;; emacs.el --- generated by `teeup theme set'; do not edit  -*- lexical-binding: t -*-
;; The next theme switch replaces this file. Loaded by
;; capabilities/emacs/default/teeup/init.el for the {{ mode }} appearance. The
;; theme name is a string passed to `intern' rather than a quoted symbol, so a
;; palette value can never close the form and run code of its own.
(setq teeup-theme-mode "{{ mode }}")
(setq teeup-theme-name (intern "{{ emacs_theme }}"))
(setq teeup-theme-colors
      '((accent . "{{ accent }}")
        (selection . "{{ selection }}")
        (muted . "{{ muted }}")
        (background . "{{ background }}")
        (dark-background . "{{ dark_background }}")
        (lighter-background . "{{ lighter_background }}")
        (foreground . "{{ foreground }}")
        (light-foreground . "{{ light_foreground }}")
        (bright-foreground . "{{ bright_foreground }}")
        (red . "{{ red }}")
        (orange . "{{ orange }}")
        (yellow . "{{ yellow }}")
        (green . "{{ green }}")
        (cyan . "{{ cyan }}")
        (blue . "{{ blue }}")
        (magenta . "{{ magenta }}")))
