# Generated by `teeup theme set`. Do not edit; the next theme switch replaces
# it. capabilities/terminal-app/theme-apply reads one "<Terminal key> <colour>"
# pair per line and builds the "teeup <Theme> <Mode>" profile from them. The
# roles are the ones WezTerm's colour scheme uses (wezterm.lua.tpl).
BackgroundColor {{ background }}
TextColor {{ foreground }}
TextBoldColor {{ bright_foreground }}
CursorColor {{ bright_foreground }}
SelectionColor {{ selection }}
ANSIBlackColor {{ dark_background }}
ANSIRedColor {{ red }}
ANSIGreenColor {{ green }}
ANSIYellowColor {{ yellow }}
ANSIBlueColor {{ blue }}
ANSIMagentaColor {{ magenta }}
ANSICyanColor {{ cyan }}
ANSIWhiteColor {{ foreground }}
ANSIBrightBlackColor {{ muted }}
ANSIBrightRedColor {{ bright_red }}
ANSIBrightGreenColor {{ bright_green }}
ANSIBrightYellowColor {{ bright_yellow }}
ANSIBrightBlueColor {{ bright_blue }}
ANSIBrightMagentaColor {{ bright_magenta }}
ANSIBrightCyanColor {{ bright_cyan }}
ANSIBrightWhiteColor {{ bright_foreground }}
